### PR TITLE
Fix https://github.com/2d-inc/Flare-Flutter/issues/75

### PR DESCRIPTION
**Pull request by truongsinh**
Fix similar to https://github.com/2d-inc/Flare-Flutter/issues/75

### CODE REVIEW

**Comment by truongsinh** [comment]
cc @luigi-rosso

**Comment by luigi-rosso** [comment]
Thanks for submitting this! I'm closing as I fixed this in the process of cleaning up a bunch of other little issues with this runtime.

**Comment by truongsinh** [comment]
@luigi-rosso then can we expect `nima` to be compatible with flutter `1.7.8+hotfix.3` anytime soon?

**Comment by luigi-rosso** [comment]
Sorry my last note wasn't clear. It is already compatible! I submitted a fix and a new build to pub. Use version 1.0.4.

**Pull request closed without merging**
